namespace Anthropic.Net;

/// <summary>
/// Represents a request validation exception. Generated by library before sending the requests to the Anthropic API.
/// </summary>
public class ValidationException : Exception
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ValidationException"/> class.
    /// </summary>
    /// <param name="message">The relevant message.</param>
    public ValidationException(string message)
        : base(message)
    {
    }
}
